# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'weibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weibo

pod 'SnapKit'
pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MLeaksFinder'
pod 'MJRefresh'
pod 'pop'
pod 'FFLabel'
pod 'FMDB'

end
